SERVER:
  GRPC:
    PORT: 10443
  HTTP:
    PORT: 10080
LOG:
  LEVEL: DEBUG
  MODE: development
MYSQL:
  HOST: 127.0.0.1
  PORT: 3307
  USERNAME: root
  PASSWORD: 123456
  DATABASE: local_db
  OPTIONS: ?parseTime=true
MIGRATION_FOLDER: file://sql/migrations
MYSQL_FULLTEXT_MIN_WORD_LENGTH: 2
TRACING:
  EXPORTERS:
    JAEGER:
      AGENT_ENDPOINT: localhost:5775
      ENABLE: true
  RATIO_BASED: 1.0
  SERVICE_NAME: CatalogV2